# https://dart-lang.github.io/linter/lints/index.html.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Erreurs
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    empty_statements: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_build_context_synchronously: true
    valid_regexps: true

    # Typo
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_final_parameters: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    library_prefixes: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_collection_literals: false
    prefer_final_fields: false
    recursive_getters: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_final: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_named_constants: true
    non_abstract_class_inherits_abstract_member: false