name: wakfu_reborn
description: Irreal infinite world
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/img/
    - assets/music/
    - assets/sound/
    - assets/json/
    - assets/sql/